name: 'marketing'

config-version: 2
version: '0.1'

profile: 'marketing'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  marketing:
      materialized: table
      staging:
        materialized: view

seeds:
  marketing:
    +schema: marketing
tests:
  +meta:
    test_suite_name: DBT TEST SUITE
    test_suite_desciption: Dbt test suite description
