name: 'marketing'

config-version: 2
version: '0.1'

profile: 'marketing'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  marketing:
    # Default materialization
    +materialized: table
    +schema: marketing  # Create models in dbt_test_marketing schema
    +tags: ['marketing_pipeline']

    # Core business models
    customers:
      +tags: ['core', 'dimension', 'customer_data', 'pii']
      +description: "Customer dimension with lifetime metrics"
    orders:
      +tags: ['core', 'fact', 'transactional', 'order_data']
      +description: "Order fact table with payment breakdowns"

    # Staging model (only stg_customer_activity remains as a model)
    stg_customer_activity:
      +materialized: view
      +tags: ['staging', 'unified', 'customer_360']
      +description: "Unified customer activity for marketing analytics"

    # Marketing analytics models
    customer_segmentation:
      +tags: ['marketing', 'customer_analytics', 'rfm', 'segmentation']
      +description: "RFM-based customer segmentation"
    product_performance:
      +tags: ['marketing', 'product_analytics', 'abc_analysis']
      +description: "Product performance and ABC classification"
    customer_cohorts:
      +tags: ['marketing', 'cohort_analysis', 'retention', 'ltv']
      +description: "Cohort retention and LTV analysis"
    marketing_attribution:
      +tags: ['marketing', 'attribution', 'channel_analytics', 'roi']
      +description: "Marketing channel attribution and ROI"

tests:
  +meta:
    test_suite_name: DBT TEST SUITE
    test_suite_desciption: Dbt test suite description
