name: 'marketing'

config-version: 2
version: '0.1'

profile: 'marketing'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  marketing:
    # Default materialization
    +materialized: table

    # Staging models as views
    stg_customers:
      +materialized: view
      +tags: ['staging']
    stg_orders:
      +materialized: view
      +tags: ['staging']
    stg_payments:
      +materialized: view
      +tags: ['staging']
    stg_customer_activity:
      +materialized: view
      +tags: ['staging']

    # Marketing analytics models
    customer_segmentation:
      +tags: ['marketing', 'customer_analytics']
    product_performance:
      +tags: ['marketing', 'product_analytics']
    customer_cohorts:
      +tags: ['marketing', 'cohort_analysis']
    marketing_attribution:
      +tags: ['marketing', 'attribution']

tests:
  +meta:
    test_suite_name: DBT TEST SUITE
    test_suite_desciption: Dbt test suite description
