name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'jaffle_shop'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  jaffle_shop:
      materialized: table
      staging:
        materialized: view

tests:
  +meta:
    test_suite_name: DBT TEST SUITE
    test_suite_desciption: Dbt test suite description
  jaffle_shop:
    # Random tests configuration - these tests produce varying results
    random_data_quality_check:
      +severity: warn  # Makes the test return warnings instead of errors
    random_customer_validation:
      +severity: warn
    random_payment_anomaly:
      +severity: error  # This one can still fail hard
