version: 2

models:
  - name: stg_customers
    description: Staging table for customer data - cleaned and standardized raw customer information
    columns:
      - name: customer_id
        description: Unique identifier for each customer
        tests:
          - unique
          - not_null

  - name: stg_orders
    description: Staging table for order data - cleaned and standardized raw order information
    columns:
      - name: order_id
        description: Unique identifier for each order
        tests:
          - unique
          - not_null
      - name: status
        description: Current status of the order (placed, shipped, completed, return_pending, returned)
        tests:
          - accepted_values:
              arguments:
                values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: cycle_name
        description: Name of the cycle associated with the order
        tests:
          - not_null

  - name: stg_payments
    description: Staging table for payment data - cleaned and standardized raw payment information
    columns:
      - name: payment_id
        description: Unique identifier for each payment transaction
        tests:
          - unique
          - not_null
      - name: payment_method
        description: Method used for payment (credit_card, coupon, bank_transfer, gift_card)
        tests:
          - accepted_values:
              arguments:
                values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']
