version: 2

models:
  # ============== CORE BUSINESS MODELS ==============
  - name: customers
    description: |
      Core customer dimension table containing customer master data with aggregated order metrics.
      This model combines customer demographic information with their lifetime purchase behavior,
      serving as the foundation for customer analytics and segmentation.
    meta:
      openmetadata:
        tier: 'Tier.Tier2'
        domain: Marketing
        owner: ['Customer Success Team']
    config:
      tags: ["customer_analytics", "core_business", "pii_data"]
    columns:
      - name: customer_id
        description: Unique customer identifier from source system
        tests:
          - unique
          - not_null
      - name: first_name
        description: Customer's first name (PII)
        tests:
          - not_null
      - name: last_name
        description: Customer's last name (PII)
        tests:
          - not_null
      - name: customer_lifetime_value
        description: Total monetary value of all customer purchases in dollars
        tests:
          - not_null
          - positive_value
      - name: first_order
        description: Date of customer's first purchase
      - name: most_recent_order
        description: Date of customer's most recent purchase
      - name: number_of_orders
        description: Total count of orders placed by the customer
        tests:
          - not_null
          - positive_value

  - name: orders
    description: |
      Transactional fact table containing order details with payment method breakdowns.
      This model enriches order data with payment information, providing a complete view
      of each transaction including payment method splits and total amounts.
    meta:
      openmetadata:
        tier: 'Tier.Tier2'
        domain: Sales
        owner: ['Sales Operations Team']
    config:
      tags: ["transactional_data", "core_business", "sales_analytics"]
    tests:
      - relationships:
          arguments:
            to: ref('customers')
            field: customer_id
    columns:
      - name: order_id
        description: Unique order transaction identifier
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Foreign key to customers dimension
        tests:
          - not_null
      - name: order_date
        description: Timestamp of order placement
        tests:
          - not_null
      - name: status
        description: Current order fulfillment status (placed, shipped, completed, returned, return_pending)
      - name: cycle_name
        description: Product name (bicycle model) associated with the order
      - name: amount
        description: Total order amount in dollars (aggregated from all payment methods)
        tests:
          - positive_value

  # ============== STAGING MODELS ==============
  - name: stg_customer_activity
    description: |
      Unified customer activity view that combines customer, order, and payment data.
      This staging model serves as the primary input for marketing analytics models,
      providing a denormalized view of customer transactions with calculated fields
      for segmentation and analysis.
    meta:
      openmetadata:
        tier: 'Tier.Tier3'
        domain: Marketing
        owner: ['Data Engineering Team']
    config:
      tags: ["staging", "marketing_prep", "customer_360"]
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
            - customer_id
            - order_id
            - payment_id
    columns:
      - name: customer_id
        description: Customer identifier linked to master customer record
        tests:
          - not_null
      - name: first_name
        description: Customer's first name from master data
      - name: last_name
        description: Customer's last name from master data
      - name: order_id
        description: Order transaction identifier
      - name: order_date
        description: Date when order was placed
      - name: status
        description: Order status in fulfillment lifecycle
      - name: cycle_name
        description: Product (bicycle model) ordered
      - name: order_status_group
        description: Simplified order status grouping (successful, returned, other)
      - name: order_month
        description: Month extracted from order date for cohort analysis
      - name: order_year
        description: Year extracted from order date for trend analysis
      - name: order_day_of_week
        description: Day of week (0=Sunday, 6=Saturday) for pattern analysis
      - name: order_quarter
        description: Quarter for seasonal analysis
      - name: customer_stage
        description: Customer lifecycle stage (new, active, loyal)
      - name: payment_id
        description: Unique payment transaction identifier
      - name: payment_method
        description: Payment type used (credit_card, coupon, bank_transfer, gift_card)
      - name: amount
        description: Payment amount in dollars
      - name: payment_category
        description: Grouped payment type (standard, promotional, other)
      - name: is_promotional
        description: Boolean flag indicating promotional payment (coupon or gift card)
      - name: cumulative_customer_value
        description: Running total of customer lifetime spend up to each order
        tests:
          - not_null
          - positive_value

  # ============== MARKETING ANALYTICS MODELS ==============
  - name: customer_segmentation
    description: |
      RFM (Recency, Frequency, Monetary) based customer segmentation model.
      Classifies customers into actionable segments for targeted marketing campaigns
      based on their purchase behavior patterns. Includes value tiers and engagement
      levels for multi-dimensional targeting strategies.
    meta:
      openmetadata:
        tier: 'Tier.Tier1'
        domain: Marketing
        owner: ['Marketing Analytics Team']
    config:
      tags: ["marketing", "customer_analytics", "segmentation", "rfm_analysis"]
    tests:
      - dbt_utils.recency:
          arguments:
            datepart: day
            field: analysis_timestamp
            interval: 1
    columns:
      - name: customer_id
        description: Unique customer identifier for joining with other models
        tests:
          - unique
          - not_null
      - name: first_name
        description: Customer's first name for personalization
      - name: last_name
        description: Customer's last name for personalization
      - name: days_since_last_order
        description: Recency metric - days elapsed since last purchase
        tests:
          - not_null
          - positive_value
      - name: total_orders
        description: Frequency metric - total number of purchases
        tests:
          - not_null
          - positive_value
      - name: total_revenue
        description: Monetary metric - total customer spend in dollars
        tests:
          - not_null
          - positive_value
      - name: avg_order_value
        description: Average transaction value per order
        tests:
          - not_null
          - positive_value
      - name: recency_score
        description: RFM recency score (1-5, where 5 is most recent)
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5]
      - name: frequency_score
        description: RFM frequency score (1-5, where 5 is most frequent)
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5]
      - name: monetary_score
        description: RFM monetary score (1-5, where 5 is highest value)
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5]
      - name: customer_segment
        description: Customer segment classification based on RFM scores
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Champions', 'Loyal Customers', 'Potential Loyalists', 'New Customers', 'Promising', 'Need Attention', 'At Risk', 'Cant Lose Them', 'Hibernating', 'Lost']
      - name: value_tier
        description: Customer value classification (High, Medium, Low)
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['High Value', 'Medium Value', 'Low Value']
      - name: engagement_level
        description: Customer engagement classification
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Highly Engaged', 'Moderately Engaged', 'Low Engagement']
      - name: promotional_spend_ratio
        description: Percentage of spend on promotional items
        tests:
          - not_null

  - name: product_performance
    description: |
      Comprehensive product analytics model tracking performance metrics across the product catalog.
      Includes sales metrics, return rates, promotional impact, market penetration, and ABC analysis
      for inventory and marketing optimization. Provides actionable insights for product strategy.
    meta:
      openmetadata:
        tier: 'Tier.Tier1'
        domain: Marketing
        owner: ['Product Team']
    config:
      tags: ["marketing", "product_analytics", "inventory_optimization", "abc_analysis"]
    tests:
      - dbt_utils.recency:
          arguments:
            datepart: day
            field: analysis_timestamp
            interval: 1
    columns:
      - name: cycle_name
        description: Product identifier (bicycle model name)
        tests:
          - unique
          - not_null
      - name: total_orders
        description: Total number of orders containing this product
        tests:
          - not_null
          - positive_value
      - name: unique_customers
        description: Count of distinct customers who purchased this product
        tests:
          - not_null
          - positive_value
      - name: total_revenue
        description: Total revenue generated by this product in dollars
        tests:
          - not_null
          - positive_value
      - name: market_penetration
        description: Percentage of total customer base that has purchased this product
        tests:
          - not_null
      - name: return_rate
        description: Percentage of orders that were returned
        tests:
          - not_null
      - name: abc_category
        description: ABC inventory classification based on revenue contribution
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['A', 'B', 'C']
      - name: product_status
        description: Product lifecycle and performance classification
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Star', 'Problem', 'Cash Cow', 'New', 'Declining', 'Standard']
      - name: revenue_rank
        description: Product ranking by total revenue (1 is highest)
        tests:
          - not_null
          - positive_value

  - name: customer_cohorts
    description: |
      Cohort-based retention and lifetime value analysis model.
      Tracks customer cohorts by acquisition month and analyzes retention patterns,
      revenue evolution, and cohort quality over time. Essential for understanding
      customer lifecycle and optimizing acquisition channel investments.
    meta:
      openmetadata:
        tier: 'Tier.Tier1'
        domain: Marketing
        owner: ['Retention Team']
    config:
      tags: ["marketing", "cohort_analysis", "retention", "ltv_analysis"]
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
            - cohort_month
            - months_since_first_purchase
    columns:
      - name: cohort_month
        description: Month when cohort was acquired (first purchase month)
        tests:
          - not_null
      - name: months_since_first_purchase
        description: Number of months elapsed since cohort acquisition
        tests:
          - not_null
      - name: cohort_size
        description: Number of customers in the acquisition cohort
        tests:
          - not_null
          - positive_value
      - name: customers_active
        description: Number of customers active in the given month
        tests:
          - not_null
      - name: retention_rate
        description: Percentage of original cohort still active
        tests:
          - not_null
      - name: cohort_revenue
        description: Total revenue from cohort in the given month
        tests:
          - not_null
      - name: cohort_quality
        description: Overall cohort quality classification
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Premium', 'High Value', 'Standard', 'Below Average', 'At Risk']
      - name: retention_stage
        description: Customer lifecycle stage classification
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Acquisition', 'Activation', 'Retention', 'Revenue', 'Referral']

  - name: marketing_attribution
    description: |
      Marketing channel attribution and performance analysis model.
      Analyzes conversion paths and channel effectiveness using synthetic attribution logic.
      Provides insights into channel ROI, customer acquisition costs, and optimal channel mix
      for marketing budget allocation.
    meta:
      openmetadata:
        tier: 'Tier.Tier1'
        domain: Marketing
        owner: ['Performance Marketing Team']
    config:
      tags: ["marketing", "attribution", "channel_performance", "roi_analysis"]
    columns:
      - name: attribution_channel
        description: Marketing channel attributed to conversions
        tests:
          - unique
          - not_null
          - accepted_values:
              arguments:
                values: ['Promotional Campaign', 'Social Media', 'Email Marketing', 'New Year Campaign', 'Organic']
      - name: total_conversions
        description: Number of successful conversions attributed to channel
        tests:
          - not_null
          - positive_value
      - name: unique_customers
        description: Number of unique customers acquired through channel
        tests:
          - not_null
          - positive_value
      - name: total_revenue
        description: Total revenue attributed to channel in dollars
        tests:
          - not_null
          - positive_value
      - name: channel_classification
        description: Performance-based channel classification
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['High Performer', 'Growth Driver', 'Premium Channel', 'Efficient Converter', 'Standard Channel']

# ============== CUSTOM TEST DEFINITIONS ==============
tests:
  - name: positive_value
    description: Ensures numeric values are positive (greater than zero)
    test: positive_value