version: 2

models:
  - name: customers
    meta:
      openmetadata:
        glossary: [
          'Customer_Data.personal_information',
          'Business_Metrics.customer_lifetime_value',
          'E_Commerce.customer_behavior',
        ]
        tier: 'Tier.Tier2'
        domain: Marketing
        customProperties:
          dbtCustomerProp: "carolyn_hill3@gmail.com"
          dbtCustomerProp2: 78
          nonAvailableCustomerProperty: nonAvailableValue
          dbtEmailid: "customer.support@jaffleshop.com"
        owner: ['Aaron Johnson', 'carolyn_hill3@gmail.com']
    config:
      tags: ["customer_analytics", "core_business", "pii_data"]
    description: >
      Customer master table with 360° view of customer analytics. Contains PII data - handle with care!
      For more details, see: https://docs.jaffleshop.com/customers & https://api.jaffleshop.com/v1/customers
      Contact: support@jaffleshop.com | Slack: #customer-analytics
    columns:
      - name: customer_id
        description: "Primary key (UUID format) for customer entity. Source: app_db.users.id @ https://github.com/dbt-labs/jaffle_shop"
        tests:
          - unique
          - not_null

      - name: first_name
        description: "Customer's first name (PII - GDPR compliant). Special chars allowed: ÄÖÜ, accents (é, ñ), hyphens, O'Brien, etc."

      - name: last_name
        description: Customer's last name. PII.

      - name: first_order
        tags: ["temporal_data", "order_analytics"]
        description: Date (UTC) of a customer's first order

      - name: most_recent_order
        description: Date (UTC) of a customer's most recent order

      - name: number_of_orders
        tags: ["kpi_metric", "customer_behavior"]
        description: Count of the number of orders a customer has placed

      - name: total_order_amount
        description: |
          Total customer lifetime value in AUD ($). Calculated as: ∑(order_amount)
          Formula: SUM(amount) WHERE status IN ('completed', 'shipped')
          Reference: https://docs.jaffleshop.com/metrics/clv#calculation-method

  - name: orders
    meta:
      openmetadata:
        glossary: [
          'E_Commerce.order_management',
          'Financial_Data.transaction_records',
          'Business_Operations.fulfillment_cycle',
        ]
        tier: 'Tier.Tier2'
        domain: Banking
        customProperties:
          dbtCustomProperty2: "carolyn_hill3@gmail.com"
          dbtProp: 78
          nonAvailableProperty: nonAvailableValue
          dbtOrderExpiration: "31/12/2025"
          dbtExpectedDuration: 6
      owner: 'Accounting'
    description: |
      Order fact table with payment breakdowns & status tracking.
      Business rules: https://confluence.jaffleshop.com/orders/business-logic
      API endpoint: POST https://api.jaffleshop.com/v2/orders/{order_id}
      Slack: #orders-team | Email: orders@jaffleshop.com
      Note: Amounts use AUD currency (A$) with 2 decimal precision
    config:
      tags: ["order_analytics", "transactional_data", "core_business"]
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
        description: "Unique order identifier (format: ORD-{timestamp}-{sequence}). See: https://github.com/dbt-labs/jaffle_shop/wiki/order-ids"

      - name: customer_id
        description: Foreign key to the customers table
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('customers')
                field: customer_id

      - name: order_date
        description: Date (UTC) that the order was placed

      - name: status
        tags: ["order_status", "workflow_tracking"]
        description: '{{ doc("orders_status") }}'
        tests:
          - accepted_values:
              arguments:
                values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

      - name: cycle_name
        description: The name of the cycle associated with the order
        tests:
          - not_null

      - name: amount
        description: Total amount (AUD) of the order
        tests:
          - not_null

      - name: credit_card_amount
        description: "CC payment amount in AUD ($). Supports Visa/MC/Amex. Fee: 2.9% + $0.30. Details: https://stripe.com/docs/payments"
        tests:
          - not_null

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon
        tests:
          - not_null

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer
        tests:
          - not_null

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card
        tests:
          - not_null

