version: 2

models:
  # ============== STAGING MODELS ==============
  # Note: stg_customers, stg_orders, stg_payments are created by base pipeline
  # and are defined as sources in sources.yml

  - name: stg_customer_activity
    description: Unified customer activity view for marketing analytics
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
            - customer_id
            - order_id
            - payment_id
    columns:
      - name: customer_id
        description: Customer identifier
        tests:
          - not_null
      - name: cumulative_customer_value
        description: Running total of customer spend
        tests:
          - not_null
          - positive_value

  # ============== MARKETING MODELS ==============
  - name: customer_segmentation
    description: RFM-based customer segmentation for targeted marketing
    meta:
      openmetadata:
        tier: 'Tier.Tier1'
        domain: Marketing
        owner: ['Marketing Analytics Team']
    config:
      tags: ["marketing", "customer_analytics", "segmentation"]
    tests:
      - dbt_utils.recency:
          arguments:
            datepart: day
            field: analysis_timestamp
            interval: 1
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests:
          - unique
          - not_null
      - name: days_since_last_order
        description: Recency metric in days
        tests:
          - not_null
          - positive_value
      - name: total_orders
        description: Frequency metric
        tests:
          - not_null
          - positive_value
      - name: total_revenue
        description: Monetary value metric
        tests:
          - not_null
          - positive_value
      - name: avg_order_value
        description: Average order value per customer
        tests:
          - not_null
          - positive_value
      - name: recency_score
        description: RFM recency score (1-5)
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5]
      - name: frequency_score
        description: RFM frequency score (1-5)
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5]
      - name: monetary_score
        description: RFM monetary score (1-5)
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5]
      - name: customer_segment
        description: Customer segment based on RFM analysis
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Champions', 'Loyal Customers', 'Potential Loyalists', 'New Customers', 'Promising', 'Need Attention', 'At Risk', 'Cant Lose Them', 'Hibernating', 'Lost']
      - name: value_tier
        description: Customer value classification
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['High Value', 'Medium Value', 'Low Value']
      - name: engagement_level
        description: Customer engagement classification
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Highly Engaged', 'Moderately Engaged', 'Low Engagement']
      - name: promotional_spend_ratio
        description: Ratio of promotional spend to total spend
        tests:
          - not_null

  - name: product_performance
    description: Comprehensive product analytics for marketing decisions
    meta:
      openmetadata:
        tier: 'Tier.Tier1'
        domain: Marketing
        owner: ['Product Marketing Team']
    config:
      tags: ["marketing", "product_analytics", "performance"]
    tests:
      - dbt_utils.recency:
          arguments:
            datepart: day
            field: analysis_timestamp
            interval: 1
    columns:
      - name: cycle_name
        description: Product name (cycle/bicycle model)
        tests:
          - unique
          - not_null
      - name: total_orders
        description: Total number of orders for product
        tests:
          - not_null
          - positive_value
      - name: unique_customers
        description: Number of unique customers who purchased
        tests:
          - not_null
          - positive_value
      - name: total_revenue
        description: Total revenue generated by product
        tests:
          - not_null
          - positive_value
      - name: return_rate
        description: Product return rate
        tests:
          - not_null
      - name: market_penetration
        description: Percentage of total customers who bought product
        tests:
          - not_null
      - name: abc_category
        description: ABC analysis category
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['A', 'B', 'C']
      - name: product_status
        description: Product lifecycle status
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Star', 'Problem', 'Cash Cow', 'New', 'Declining', 'Standard']
      - name: revenue_rank
        description: Product ranking by revenue
        tests:
          - not_null
          - positive_value

  - name: customer_cohorts
    description: Cohort analysis for retention and LTV tracking
    meta:
      openmetadata:
        tier: 'Tier.Tier1'
        domain: Marketing
        owner: ['Retention Team']
    config:
      tags: ["marketing", "cohort_analysis", "retention"]
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
            - cohort_month
            - months_since_first_purchase
    columns:
      - name: cohort_month
        description: Month when cohort started
        tests:
          - not_null
      - name: months_since_first_purchase
        description: Months elapsed since cohort start
        tests:
          - not_null
      - name: cohort_size
        description: Original size of cohort
        tests:
          - not_null
          - positive_value
      - name: customers_active
        description: Number of active customers in period
        tests:
          - not_null
      - name: retention_rate
        description: Percentage of cohort retained
        tests:
          - not_null
      - name: cohort_revenue
        description: Revenue generated by cohort in period
        tests:
          - not_null
      - name: cohort_quality
        description: Quality classification of cohort
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Premium', 'High Value', 'Standard', 'Below Average', 'At Risk']
      - name: retention_stage
        description: Stage in customer lifecycle
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Acquisition', 'Activation', 'Retention', 'Revenue', 'Referral']

  - name: marketing_attribution
    description: Marketing channel attribution and performance analysis
    meta:
      openmetadata:
        tier: 'Tier.Tier1'
        domain: Marketing
        owner: ['Performance Marketing Team']
    config:
      tags: ["marketing", "attribution", "channel_performance"]
    columns:
      - name: attribution_channel
        description: Marketing channel attribution
        tests:
          - unique
          - not_null
          - accepted_values:
              arguments:
                values: ['Promotional Campaign', 'Social Media', 'Email Marketing', 'New Year Campaign', 'Organic']
      - name: total_conversions
        description: Total conversions by channel
        tests:
          - not_null
          - positive_value
      - name: unique_customers
        description: Unique customers acquired
        tests:
          - not_null
          - positive_value
      - name: total_revenue
        description: Revenue attributed to channel
        tests:
          - not_null
          - positive_value
      - name: channel_classification
        description: Performance-based channel classification
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['High Performer', 'Growth Driver', 'Premium Channel', 'Efficient Converter', 'Standard Channel']

  # ============== CORE BUSINESS MODELS ==============
  - name: customers
    description: Customer 360 view with lifetime value metrics
    meta:
      openmetadata:
        tier: 'Tier.Tier2'
        domain: Marketing
        owner: ['Customer Success Team']
    config:
      tags: ["customer_analytics", "core_business", "pii_data"]
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests:
          - unique
          - not_null
      - name: first_order
        description: Date of first order
        tests:
          - not_null
      - name: most_recent_order
        description: Date of most recent order
        tests:
          - not_null
      - name: number_of_orders
        description: Total number of orders
        tests:
          - not_null
          - positive_value
      - name: customer_lifetime_value
        description: Total customer spend
        tests:
          - not_null
          - positive_value

  - name: orders
    description: Order-level analytics with payment method breakdown
    meta:
      openmetadata:
        tier: 'Tier.Tier2'
        domain: Operations
        owner: ['Operations Team']
    config:
      tags: ["order_analytics", "transactional_data", "core_business"]
    columns:
      - name: order_id
        description: Unique order identifier
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Foreign key to customers
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('customers')
                field: customer_id
      - name: order_date
        description: Date of order
        tests:
          - not_null
      - name: amount
        description: Total order amount
        tests:
          - not_null
          - positive_value