version: 2

sources:
  - name: dbt_production
    description: |
      Production data sources including raw tables and staging views created by the base dbt pipeline.
      These sources serve as the foundation for all marketing analytics transformations.
      Raw tables are not directly accessible; staging views provide the cleaned and standardized data.
    database: "{{ target.database }}"
    schema: dbt_production
    meta:
      owner: "Marketing Analytics Team"
      domain: "Marketing"
      data_classification: "Internal"
      pipeline_source: "Base ETL Pipeline"
    tags: ["source_data", "base_pipeline", "external_dependency"]

    tables:
      # Raw tables - these don't actually exist in our environment
      # The base pipeline creates staging views directly
      - name: customers
        description: Customer master data with demographic information (raw table - not accessible)
        meta:
          contains_pii: true
          refresh_frequency: "daily"
        columns:
          - name: id
            description: Unique customer identifier
          - name: first_name
            description: Customer first name
          - name: last_name
            description: Customer last name

      - name: orders
        description: Order transaction data with product details (raw table - not accessible)
        meta:
          refresh_frequency: "hourly"
        columns:
          - name: id
            description: Unique order identifier
          - name: user_id
            description: Foreign key to customers table
          - name: order_date
            description: Date when the order was placed
          - name: status
            description: Current order status in the fulfillment process
          - name: cycle_name
            description: Product name (bicycle model) for the order

      - name: payments
        description: Payment transaction data with amounts and methods (raw table - not accessible)
        meta:
          refresh_frequency: "real-time"
        columns:
          - name: id
            description: Unique payment identifier
          - name: order_id
            description: Foreign key to orders table
          - name: payment_method
            description: Payment method used for the transaction
          - name: amount
            description: Payment amount in cents
          - name: cycle_name
            description: Product name associated with this payment

      # Staging views created by base dbt pipeline
      - name: stg_customers
        description: |
          Staging view for customer data with standardized column names and data types.
          Created by the base dbt pipeline, this view provides clean customer master data
          with consistent naming conventions and data quality checks already applied.
        meta:
          created_by: "base_pipeline"
          refresh_frequency: "daily"
          contains_pii: true
        tags: ["staging", "customer_data", "pii"]
        columns:
          - name: customer_id
            description: Standardized customer identifier
            tests:
              - unique
              - not_null
          - name: first_name
            description: Customer first name
            tests:
              - not_null
          - name: last_name
            description: Customer last name
            tests:
              - not_null

      - name: stg_orders
        description: |
          Staging view for order transactions with standardized formatting.
          Provides clean order data with proper data types, consistent status values,
          and foreign key relationships to customers. Core transactional fact data.
        meta:
          created_by: "base_pipeline"
          refresh_frequency: "hourly"
          data_quality: "high"
        tags: ["staging", "transactional_data", "order_data"]
        columns:
          - name: order_id
            description: Standardized order identifier
            tests:
              - unique
              - not_null
          - name: customer_id
            description: Foreign key to customer
            tests:
              - not_null
          - name: order_date
            description: Date of order placement
            tests:
              - not_null
          - name: status
            description: Order status
            tests:
              - not_null
          - name: cycle_name
            description: Product ordered (bicycle model)
            tests:
              - not_null

      - name: stg_payments
        description: |
          Staging view for payment transactions with standardized payment methods.
          Includes amount conversions (cents to dollars) and validated payment types.
          Links to orders for complete transaction visibility.
        meta:
          created_by: "base_pipeline"
          refresh_frequency: "real-time"
          data_sensitivity: "financial"
        tags: ["staging", "payment_data", "financial"]
        columns:
          - name: payment_id
            description: Standardized payment identifier
            tests:
              - unique
              - not_null
          - name: order_id
            description: Foreign key to orders
            tests:
              - not_null
          - name: payment_method
            description: Payment method used
            tests:
              - not_null
          - name: cycle_name
            description: Product associated with payment
            tests:
              - not_null
          - name: amount
            description: Payment amount in dollars
            tests:
              - not_null